---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aargh64
  name: aargh64
  namespace: default
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: aargh64
  template:
    metadata:
      name: aargh64
      labels:
        app: aargh64
    spec:
      serviceAccount: aargh64
      containers:
      - name: main
        image: aargh64-debug:latest
        imagePullPolicy: Never
        env:
        - name: RUST_LOG
          value: info
        ports:
        - containerPort: 8443
          name: main
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: aargh64
  name: aargh64
  namespace: default
spec:
  ports:
  - name: aargh64-main
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: aargh64
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: aargh64
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: secrets-reader
rules:
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs:
  - list
  - get
  - watch
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: platformoverrides-reader
rules:
- apiGroups:
  - "aargh64.akquinet.de"
  resources:
  - "platformoverrides"
  verbs:
  - list
  - get
  - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: aargh64-secrets-reader

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secrets-reader
subjects:
- kind: ServiceAccount
  namespace: default
  name: aargh64
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: aargh64-platformoverrides-reader

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: platformoverrides-reader
subjects:
- kind: ServiceAccount
  namespace: default
  name: aargh64
