name: "Build"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: actions/cache@v3
      with:
        path: /nix/store
        key: nix-store-${{ runner.os }}-${{ runner.arch }}
    - uses: cachix/install-nix-action@v15
      with:
        extra_nix_config: |
          system-features = nixos-test benchmark big-parallel kvm
    - run: nix build .#aargh64-docker
